steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "DATABASE_URL=$$DATABASE_URL" > .env
      echo "NEXT_PUBLIC_BASE_URL=beta.abrico.eco" >> .env
      # FIXME delete the following lines once we use sendgrid
      echo "EMAIL_SERVER=localhost" >> .env
      echo "EMAIL_FROM=support@abrico.eco" >> .env
    secretEnv: ['DATABASE_URL']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/abrico-app-prod:$COMMIT_SHA', '.' ]
    env: ['DOCKER_BUILDKIT=1']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/abrico-app-prod:$COMMIT_SHA' ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'abrico-app-prod'
      - '--image'
      - 'gcr.io/$PROJECT_ID/abrico-app-prod:$COMMIT_SHA'
      - '--region'
      - 'europe-west9'

availableSecrets:
  secretManager:
    - versionName: projects/abrico-418714/secrets/abrico-db-prod-rw-uri/versions/1
      env: 'DATABASE_URL'

images:
  - 'gcr.io/$PROJECT_ID/abrico-app-prod:$COMMIT_SHA'
